/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenizationTaskHttpRequest1 {
    #[serde(rename = "inputs")]
    pub inputs: String,
    #[serde(rename = "model_id")]
    pub model_id: String,
}

impl TokenizationTaskHttpRequest1 {
    pub fn new(inputs: String, model_id: String) -> TokenizationTaskHttpRequest1 {
        TokenizationTaskHttpRequest1 { inputs, model_id }
    }
}
