repos:
  - repo: https://github.com/foundation-model-stack/fms-guardrails-orchestrator/
    rev: 0dddef079cb092ebdfaa57e6a8b091a3eaf617ae
    hooks:
      - id: fmt-nightly
      - id: cargo-check
      - id: clippy